import test from 'node:test'
import assert from 'node:assert/strict'
import { DEFAULT_DECISION_EFFECT, DECISION_ENTER_MS, DECISION_EXIT_MS, DecisionEffectController, normalizeDecisionEffect } from '../src/prototype/decisionEffect.ts'

test('decision effect normalizes the scrub range and branch', () => {
  assert.deepEqual(normalizeDecisionEffect({ active: true, horizon: 9, branch: 2, comparing: true, emphasis: -1 }), {
    active: true, horizon: 1, branch: 2, comparing: true, emphasis: 0,
  })
  assert.deepEqual(normalizeDecisionEffect({}), DEFAULT_DECISION_EFFECT)
})

test('selected route changes physical shape and comparison restores baseline', () => {
  const effect = new DecisionEffectController()
  effect.setDetail({ active: true, horizon: 1, branch: 2, emphasis: 1 })
  effect.advance(1, true)
  const selected = effect.getSnapshot(true)
  assert.ok(selected.warpHeight > 1)
  assert.ok(selected.lensStrength > 0)
  assert.ok(selected.radiusScale > 1)
  effect.setDetail({ active: true, horizon: 1, branch: 2, comparing: true, emphasis: 1 })
  effect.advance(0, true)
  const baseline = effect.getSnapshot(true)
  assert.equal(baseline.deformation, 0)
  assert.equal(baseline.lensStrength, 0)
})

test('leaving the studio clears deformation and stops effect frames', () => {
  const effect = new DecisionEffectController()
  effect.setDetail({ active: true, horizon: .7, branch: 1 })
  effect.advance(1, true)
  effect.setDetail({ active: false })
  assert.equal(effect.getSnapshot(true).active, false)
  assert.equal(effect.getSnapshot(true).deformation, 0)
  assert.equal(effect.needsFrame(false), false)
})

test('scrubbing and branch reversal are continuous and settle independently of frame rate', () => {
  const slow = new DecisionEffectController(), fast = new DecisionEffectController()
  for (const effect of [slow, fast]) effect.setDetail({ active: true, horizon: 1, branch: 2 })
  for (let i = 0; i < 60; i++) slow.advance(1 / 30)
  for (let i = 0; i < 240; i++) fast.advance(1 / 120)
  assert.ok(Math.abs(slow.getSnapshot().radiusScale - fast.getSnapshot().radiusScale) < .00001)
  const before = fast.getSnapshot()
  fast.setDetail({ active: true, horizon: .1, branch: 0 })
  assert.equal(fast.getSnapshot().radiusScale, before.radiusScale)
  fast.advance(1 / 60)
  assert.ok(fast.getSnapshot().renderedHorizon < before.renderedHorizon)
  assert.ok(fast.getSnapshot().renderedHorizon > .1)
})

test('reduced motion preserves direct shape feedback and never runs an effect clock', () => {
  const effect = new DecisionEffectController()
  effect.setDetail({ active: true, horizon: 1, branch: 2, emphasis: 1 })
  effect.advance(.1, true)
  const far = effect.getSnapshot(true)
  effect.advance(60, true)
  assert.equal(effect.getSnapshot(true).time, 0)
  assert.equal(effect.needsFrame(true), false)
  effect.setDetail({ active: true, horizon: .1, branch: 0, emphasis: 0 })
  effect.advance(0, true)
  assert.notEqual(effect.getSnapshot(true).radiusScale, far.radiusScale)
  assert.notEqual(effect.getSnapshot(true).inclinationOffset, far.inclinationOffset)
})

test('compare release returns to the selected route and exit restores every shape uniform', () => {
  const effect = new DecisionEffectController()
  const detail = { active: true, horizon: .8, branch: 1, emphasis: .5 }
  effect.setDetail(detail)
  effect.advance(0, true)
  const selected = effect.getSnapshot(true)
  effect.setDetail({ ...detail, comparing: true })
  effect.advance(0, true)
  assert.equal(effect.getSnapshot(true).radiusScale, 1)
  assert.equal(effect.getSnapshot(true).warpHeight, 0)
  effect.setDetail(detail)
  effect.advance(0, true)
  assert.deepEqual(effect.getSnapshot(true), selected)
  effect.setDetail({ active: false })
  const original = effect.getSnapshot()
  assert.equal(original.radiusScale, 1)
  assert.equal(original.warpHeight, 0)
  assert.equal(original.diskThickness, 1)
  assert.equal(original.lensStrength, 0)
  assert.equal(original.flowSpeed, 1)
  assert.equal(original.inclinationOffset, 0)
})

function enterDecision(effect) {
  effect.setDetail({ active: true, horizon: .8, branch: 2, emphasis: .7 })
  for (let frame = 0; frame < 120; frame++) effect.advance(1 / 60)
  return effect.getSnapshot()
}

test('decision exit keeps the scene active while shape and camera retreat at homepage pace', () => {
  const effect = new DecisionEffectController()
  const entered = enterDecision(effect)
  assert.equal(entered.strength, 1)
  effect.beginExit()
  assert.equal(effect.getSnapshot().active, true)
  assert.equal(effect.getSnapshot().strength, entered.strength)
  effect.advance(DECISION_EXIT_MS / 2000)
  const halfway = effect.getSnapshot()
  assert.equal(halfway.exiting, true)
  assert.equal(halfway.active, true)
  assert.equal(halfway.exitProgress, .5)
  assert.ok(halfway.strength > .17 && halfway.strength < .18)
  assert.ok(Math.abs(halfway.inclinationOffset / entered.inclinationOffset - halfway.strength) < 1e-10)
  assert.ok(halfway.warpHeight > 0 && halfway.warpHeight < entered.warpHeight)
  assert.equal(effect.needsFrame(false), true)
  effect.advance(DECISION_EXIT_MS / 2000)
  const exited = effect.getSnapshot()
  assert.equal(exited.active, false)
  assert.equal(exited.exiting, false)
  assert.equal(exited.strength, 0)
  assert.equal(exited.warpHeight, 0)
  assert.equal(exited.radiusScale, 1)
  assert.equal(exited.inclinationOffset, 0)
  assert.equal(effect.needsFrame(false), false)
})

test('long frames complete exit using real elapsed time, while a repeated exit cannot restart it', () => {
  const effect = new DecisionEffectController()
  enterDecision(effect)
  effect.beginExit()
  effect.advance(.12)
  const before = effect.getSnapshot()
  effect.beginExit()
  assert.equal(effect.getSnapshot().strength, before.strength)
  assert.equal(effect.getSnapshot().exitProgress, before.exitProgress)
  effect.advance(5)
  assert.equal(effect.getSnapshot().active, false)
  assert.equal(effect.getSnapshot().strength, 0)
})

test('returning during exit cancels the retreat without jumping the current shape', () => {
  const effect = new DecisionEffectController()
  enterDecision(effect)
  effect.beginExit()
  effect.advance(.1)
  const exiting = effect.getSnapshot()
  effect.setDetail({ active: true, horizon: .8, branch: 2, emphasis: .7 })
  assert.equal(effect.getSnapshot().exiting, false)
  assert.equal(effect.getSnapshot().strength, exiting.strength)
  assert.equal(effect.getSnapshot().warpHeight, exiting.warpHeight)
  effect.advance(1 / 60)
  assert.ok(effect.getSnapshot().strength > exiting.strength)
  assert.ok(effect.getSnapshot().strength < 1)
  for (let frame = 0; frame < 120; frame++) effect.advance(1 / 60)
  assert.equal(effect.getSnapshot().strength, 1)
  assert.equal(effect.getSnapshot().active, true)
})

test('reduced motion and paused exit complete immediately, including a mid-exit preference change', () => {
  for (const [reduced, paused] of [[true, false], [false, true]]) {
    const effect = new DecisionEffectController()
    enterDecision(effect)
    effect.beginExit(reduced, paused)
    assert.equal(effect.getSnapshot().active, false)
    assert.equal(effect.getSnapshot().strength, 0)
    enterDecision(effect)
    effect.beginExit()
    effect.advance(.04)
    effect.advance(0, reduced, paused)
    assert.equal(effect.getSnapshot().active, false)
    assert.equal(effect.getSnapshot().strength, 0)
  }
})

test('hard active:false cleanup still interrupts a pending retreat without residual shape', () => {
  const effect = new DecisionEffectController()
  enterDecision(effect)
  effect.beginExit()
  effect.advance(.05)
  effect.setDetail({ active: false })
  effect.advance(.1)
  assert.equal(effect.getSnapshot().active, false)
  assert.equal(effect.getSnapshot().exiting, false)
  assert.equal(effect.getSnapshot().strength, 0)
  assert.equal(effect.getSnapshot().lensStrength, 0)
  assert.equal(effect.getSnapshot().radiusScale, 1)
})


test('entry and retreat share homepage timing, with a finite gentle landing', () => {
  const effect = new DecisionEffectController()
  effect.setDetail({ active: true, horizon: .8, branch: 2, emphasis: .7 })
  effect.advance(.15)
  assert.ok(effect.getSnapshot().strength > .09 && effect.getSnapshot().strength < .11)
  // Reading or interacting with the same scene must not restart its entrance.
  effect.setDetail({ active: true, horizon: .9, branch: 2, emphasis: 1 })
  effect.advance(.33)
  assert.ok(effect.getSnapshot().strength > .49 && effect.getSnapshot().strength < .51)
  effect.advance(.631)
  assert.ok(effect.getSnapshot().strength > .89 && effect.getSnapshot().strength < .91)
  effect.advance(DECISION_ENTER_MS / 1000 - 1.111)
  assert.equal(effect.getSnapshot().strength, 1)
  enterDecision(effect)
  effect.beginExit()
  effect.advance(.15)
  assert.ok(effect.getSnapshot().strength > .89 && effect.getSnapshot().strength < .91)
  effect.advance(.33)
  assert.ok(effect.getSnapshot().strength > .49 && effect.getSnapshot().strength < .51)
  effect.advance(.631)
  assert.ok(effect.getSnapshot().strength > .09 && effect.getSnapshot().strength < .11)
  effect.advance(DECISION_EXIT_MS / 1000 - 1.111 - 1 / 60)
  const lastFrame = effect.getSnapshot()
  assert.ok(lastFrame.strength > 0 && lastFrame.strength < .001)
  // At a normal frame cadence the final hard cleanup is below visible camera
  // precision: < .0004 zoom units, < .03 degrees for the largest tilt.
  assert.ok(Math.abs(lastFrame.inclinationOffset) < .03)
  effect.setDetail({ active: false })
  assert.equal(effect.getSnapshot().strength, 0)
})
